import type { VoiceState, StateConfig } from '../types';

export const STATE_CONFIGS: Record<VoiceState, StateConfig> = {
  IDLE: {
    label: 'Ready / Standby',
    description: 'Tap microphone or start speaking to begin',
    badgeBg: 'bg-slate-800/80',
    badgeText: 'text-slate-300',
    borderColor: 'border-slate-700/60',
    ringColor: 'ring-slate-600/30',
    glowColor: 'shadow-slate-500/10',
  },
  CONNECTING: {
    label: 'Connecting WebRTC',
    description: 'Establishing low-latency peer connection...',
    badgeBg: 'bg-amber-950/50',
    badgeText: 'text-amber-300',
    borderColor: 'border-amber-600/60',
    ringColor: 'ring-amber-500/40',
    glowColor: 'shadow-amber-500/20',
  },
  LISTENING: {
    label: 'Listening...',
    description: 'Mic active • Detecting speech in EN / HI / Hinglish',
    badgeBg: 'bg-emerald-950/60',
    badgeText: 'text-emerald-300',
    borderColor: 'border-emerald-500/70',
    ringColor: 'ring-emerald-500/50',
    glowColor: 'shadow-emerald-500/30',
  },
  THINKING: {
    label: 'Thinking...',
    description: 'Processing speech turn & generating response',
    badgeBg: 'bg-indigo-950/60',
    badgeText: 'text-indigo-300',
    borderColor: 'border-indigo-500/70',
    ringColor: 'ring-indigo-500/50',
    glowColor: 'shadow-indigo-500/30',
  },
  SPEAKING: {
    label: 'Speaking',
    description: 'Streaming audio synthesis • Interrupt anytime',
    badgeBg: 'bg-cyan-950/60',
    badgeText: 'text-cyan-300',
    borderColor: 'border-cyan-500/70',
    ringColor: 'ring-cyan-500/50',
    glowColor: 'shadow-cyan-500/30',
  },
  ERROR: {
    label: 'Connection Error',
    description: 'Failed to connect. Please check permissions.',
    badgeBg: 'bg-rose-950/60',
    badgeText: 'text-rose-300',
    borderColor: 'border-rose-500/70',
    ringColor: 'ring-rose-500/50',
    glowColor: 'shadow-rose-500/30',
  },
};
